import { collection, doc, getDoc, getDocs, query, runTransaction, serverTimestamp, setDoc, updateDoc, where, writeBatch } from 'firebase/firestore'
import { db } from '../firebase'
import { ACTIVE_BOOKING_STATUSES } from '../constants/booking'
import { bookingNumber, enumerateNights } from '../utils/booking'
const requireDb=()=>{if(!db)throw new Error('Firebase is not configured.')}
const plain=(snap)=>snap.exists()?{id:snap.id,...snap.data()}:null
export async function createBooking(input){ requireDb(); const id=crypto.randomUUID(); const number=bookingNumber(); const nights=enumerateNights(input.checkIn,input.checkOut); return runTransaction(db,async tx=>{ for(const date of nights){ const lockRef=doc(db,'availability',`${input.roomId}_${date}`); const lock=await tx.get(lockRef); if(lock.exists()&&ACTIVE_BOOKING_STATUSES.includes(lock.data().bookingStatus)) throw new Error(`Room unavailable on ${date}. Choose different dates.`) }
 const bookingRef=doc(db,'bookings',id); const payload={...input,id,bookingNumber:number,status:'pending',paymentStatus:'pending',bookingSource:'web',createdAt:serverTimestamp(),updatedAt:serverTimestamp()}; tx.set(bookingRef,payload); nights.forEach(date=>tx.set(doc(db,'availability',`${input.roomId}_${date}`),{id:`${input.roomId}_${date}`,roomId:input.roomId,propertyId:input.propertyId,ownerId:input.ownerId,guestId:input.guestId,bookingId:id,date,type:'booking',bookingStatus:'pending',createdAt:serverTimestamp(),updatedAt:serverTimestamp()})); tx.set(doc(db,'bookingTimeline',`${id}_created`),{bookingId:id,guestId:input.guestId,ownerId:input.ownerId,status:'pending',label:'Booking created',createdAt:serverTimestamp()}); tx.set(doc(db,'bookingReceipts',id),{bookingId:id,receiptNumber:`RCT-${number}`,guestId:input.guestId,ownerId:input.ownerId,createdAt:serverTimestamp()}); tx.set(doc(db,'notifications',`${id}_owner`),{recipientId:input.ownerId,type:'new_booking',bookingId:id,title:'New booking request',message:`${number} requires your review.`,read:false,createdAt:serverTimestamp()}); tx.set(doc(db,'notifications',`${id}_guest`),{recipientId:input.guestId,type:'booking_created',bookingId:id,title:'Booking created',message:`${number} is pending owner confirmation.`,read:false,createdAt:serverTimestamp()}); return {id,...payload,bookingNumber:number} }) }
export async function getBooking(id){requireDb();return plain(await getDoc(doc(db,'bookings',id)))}
export async function listGuestBookings(uid){if(!db)return[]; const snap=await getDocs(query(collection(db,'bookings'),where('guestId','==',uid))); return snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0))}
export async function listBookingTimeline(bookingId){if(!db)return[]; const snap=await getDocs(query(collection(db,'bookingTimeline'),where('bookingId','==',bookingId))); return snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.createdAt?.seconds||0)-(b.createdAt?.seconds||0))}
export async function cancelGuestBooking(booking,uid){requireDb(); if(booking.guestId!==uid)throw new Error('You cannot cancel this booking.'); if(!['pending','confirmed'].includes(booking.status))throw new Error('This booking can no longer be cancelled.'); const batch=writeBatch(db); batch.update(doc(db,'bookings',booking.id),{status:'cancelled',updatedAt:serverTimestamp()}); enumerateNights(booking.checkIn,booking.checkOut).forEach(date=>batch.delete(doc(db,'availability',`${booking.roomId}_${date}`))); batch.set(doc(db,'bookingTimeline',`${booking.id}_cancelled_${Date.now()}`),{bookingId:booking.id,guestId:booking.guestId,ownerId:booking.ownerId,status:'cancelled',label:'Booking cancelled by guest',createdAt:serverTimestamp()}); batch.set(doc(db,'notifications',`${booking.id}_cancel_${Date.now()}`),{recipientId:booking.ownerId,type:'booking_cancelled',bookingId:booking.id,title:'Booking cancelled',message:`${booking.bookingNumber} was cancelled by the guest.`,read:false,createdAt:serverTimestamp()}); return batch.commit()}
export async function setOwnerBookingStatus(booking,ownerId,status){requireDb();if(booking.ownerId!==ownerId)throw new Error('You cannot manage this booking.'); const allowed={pending:['confirmed','rejected'],confirmed:['checked_in','cancelled'],checked_in:['checked_out'],checked_out:['completed']}[booking.status]||[]; if(!allowed.includes(status))throw new Error('Invalid booking status transition.'); const batch=writeBatch(db); batch.update(doc(db,'bookings',booking.id),{status,updatedAt:serverTimestamp()}); batch.set(doc(db,'bookingTimeline',`${booking.id}_${status}_${Date.now()}`),{bookingId:booking.id,guestId:booking.guestId,ownerId,status,label:`Booking ${status.replace('_',' ')}`,createdAt:serverTimestamp()}); if(['rejected','cancelled'].includes(status)) enumerateNights(booking.checkIn,booking.checkOut).forEach(date=>batch.delete(doc(db,'availability',`${booking.roomId}_${date}`))); else enumerateNights(booking.checkIn,booking.checkOut).forEach(date=>batch.update(doc(db,'availability',`${booking.roomId}_${date}`),{bookingStatus:status,updatedAt:serverTimestamp()})); batch.set(doc(db,'notifications',`${booking.id}_${status}_${Date.now()}`),{recipientId:booking.guestId,type:`booking_${status}`,bookingId:booking.id,title:`Booking ${status.replace('_',' ')}`,message:`${booking.bookingNumber} is now ${status.replace('_',' ')}.`,read:false,createdAt:serverTimestamp()}); return batch.commit()}
export async function saveBookingDraft(uid,data){requireDb();return setDoc(doc(db,'bookingDrafts',uid),{...data,guestId:uid,updatedAt:serverTimestamp()},{merge:true})}
export async function updateBookingPayment(id,paymentStatus){requireDb();return updateDoc(doc(db,'bookings',id),{paymentStatus,updatedAt:serverTimestamp()})}
