import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, limit, query, serverTimestamp, setDoc, updateDoc, where, writeBatch } from 'firebase/firestore'
import { deleteObject, getDownloadURL, ref, uploadBytes } from 'firebase/storage'
import { db, storage } from '../firebase'
const needDb=()=>{if(!db)throw new Error('Firebase Firestore is not configured.')}
const rows=s=>s.docs.map(d=>({id:d.id,...d.data()}))
export async function listFavorites(uid){if(!db)return[];return rows(await getDocs(query(collection(db,'favorites'),where('userId','==',uid),limit(100))))}
export async function addFavorite(uid,property){needDb();const id=`${uid}_${property.id}`;return setDoc(doc(db,'favorites',id),{id,userId:uid,propertyId:property.id,propertyName:property.name||property.propertyName||'Property',propertyImage:property.image||property.coverImage||'',village:property.village||property.location||'Sohra',price:Number(property.price||0),rating:Number(property.rating||0),createdAt:serverTimestamp()})}
export async function removeFavorite(uid,propertyId){needDb();return deleteDoc(doc(db,'favorites',`${uid}_${propertyId}`))}
export async function isFavorite(uid,propertyId){if(!db)return false;return (await getDoc(doc(db,'favorites',`${uid}_${propertyId}`))).exists()}
export async function listRecentlyViewed(uid){if(!db)return[];return rows(await getDocs(query(collection(db,'recentlyViewed'),where('userId','==',uid),limit(20)))).sort((a,b)=>(b.viewedAt?.seconds||0)-(a.viewedAt?.seconds||0))}
export async function trackRecentlyViewed(uid,property){needDb();return setDoc(doc(db,'recentlyViewed',`${uid}_${property.id}`),{id:`${uid}_${property.id}`,userId:uid,propertyId:property.id,propertyName:property.name||'Property',propertyImage:property.image||property.coverImage||'',village:property.village||property.location||'Sohra',price:Number(property.price||0),viewedAt:serverTimestamp()})}
export async function removeRecentlyViewed(uid,propertyId){needDb();return deleteDoc(doc(db,'recentlyViewed',`${uid}_${propertyId}`))}
export async function clearRecentlyViewed(uid){needDb();const snap=await getDocs(query(collection(db,'recentlyViewed'),where('userId','==',uid)));const batch=writeBatch(db);snap.forEach(d=>batch.delete(d.ref));return batch.commit()}
export async function listNotifications(uid){if(!db)return[];return rows(await getDocs(query(collection(db,'notifications'),where('recipientId','==',uid),limit(100)))).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0))}
export async function markNotificationRead(uid,id){needDb();const r=doc(db,'notifications',id);const snap=await getDoc(r);if(!snap.exists()||snap.data().recipientId!==uid)throw new Error('Notification not found.');return updateDoc(r,{read:true})}
export async function markAllNotificationsRead(uid){needDb();const snap=await getDocs(query(collection(db,'notifications'),where('recipientId','==',uid)));const batch=writeBatch(db);snap.forEach(d=>{if(!d.data().read)batch.update(d.ref,{read:true})});return batch.commit()}
export async function deleteNotification(uid,id){needDb();const r=doc(db,'notifications',id);const snap=await getDoc(r);if(!snap.exists()||snap.data().recipientId!==uid)throw new Error('Notification not found.');return deleteDoc(r)}
export async function getGuestSettings(uid){if(!db)return null;const s=await getDoc(doc(db,'guestSettings',uid));return s.exists()?{id:s.id,...s.data()}:null}
export async function saveGuestSettings(uid,data){needDb();return setDoc(doc(db,'guestSettings',uid),{userId:uid,...data,updatedAt:serverTimestamp()},{merge:true})}
export async function listGuestReviews(uid){if(!db)return[];return rows(await getDocs(query(collection(db,'reviews'),where('guestId','==',uid),limit(100)))).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0))}
export async function saveReview(uid,booking,data){needDb();if(booking.guestId!==uid||booking.status!=='completed')throw new Error('Only completed bookings can be reviewed.');const existing=await getDocs(query(collection(db,'reviews'),where('bookingId','==',booking.id),where('guestId','==',uid),limit(1)));const payload={guestId:uid,bookingId:booking.id,propertyId:booking.propertyId,ownerId:booking.ownerId,propertyName:booking.propertyName,roomName:booking.roomName,...data,updatedAt:serverTimestamp()};if(existing.empty)return addDoc(collection(db,'reviews'),{...payload,createdAt:serverTimestamp()});return updateDoc(existing.docs[0].ref,payload)}
export async function deleteReview(uid,id){needDb();const r=doc(db,'reviews',id);const s=await getDoc(r);if(!s.exists()||s.data().guestId!==uid)throw new Error('Review not found.');return deleteDoc(r)}
export async function uploadReviewPhoto(uid,file){if(!storage)throw new Error('Firebase Storage is not configured.');if(!file.type.startsWith('image/')||file.size>5*1024*1024)throw new Error('Use an image up to 5 MB.');const p=ref(storage,`review-images/${uid}/${crypto.randomUUID()}-${file.name}`);await uploadBytes(p,file,{contentType:file.type});return getDownloadURL(p)}
export async function deleteReviewPhoto(url){if(!storage||!url)return;try{await deleteObject(ref(storage,url))}catch(e){if(e.code!=='storage/object-not-found')throw e}}
