const shell = ({ heading, intro, body, actionLabel, actionUrl }) => `<!doctype html><html><body style="margin:0;background:#fffdf5;font-family:Arial,sans-serif;color:#2d2d2d"><table role="presentation" width="100%"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="100%" style="max-width:620px;background:white;border-radius:24px;overflow:hidden"><tr><td style="background:#fff380;padding:24px;font-size:24px;font-weight:800">DONROOM</td></tr><tr><td style="padding:32px"><h1>${heading}</h1><p>${intro}</p>${body}${actionUrl ? `<p style="margin-top:28px"><a href="${actionUrl}" style="background:#2d2d2d;color:white;padding:13px 20px;border-radius:999px;text-decoration:none;font-weight:700">${actionLabel}</a></p>` : ''}<p style="margin-top:32px;color:#666;font-size:13px">DONROOM · Verified stays in Sohra, Meghalaya</p></td></tr></table></td></tr></table></body></html>`

export const emailTemplates = Object.freeze({
  welcome: (data) => shell({ heading: `Welcome to DONROOM, ${data.fullName}`, intro: 'Your account is ready.', body: '<p>Explore verified local stays and manage every trip from your guest dashboard.</p>', actionLabel: 'Explore stays', actionUrl: data.actionUrl }),
  bookingConfirmation: (data) => shell({ heading: 'Booking request received', intro: `Booking ${data.bookingNumber} is pending owner confirmation.`, body: `<p><strong>${data.propertyName}</strong><br>${data.checkIn} to ${data.checkOut}<br>Total: ₹${data.grandTotal}</p>`, actionLabel: 'View booking', actionUrl: data.actionUrl }),
  bookingAccepted: (data) => shell({ heading: 'Your booking is confirmed', intro: `Booking ${data.bookingNumber} has been accepted.`, body: `<p>We look forward to welcoming you to ${data.propertyName}.</p>`, actionLabel: 'View trip', actionUrl: data.actionUrl }),
  bookingRejected: (data) => shell({ heading: 'Booking request declined', intro: `Booking ${data.bookingNumber} was not accepted.`, body: `<p>${data.reason || 'The property could not confirm this stay.'}</p>`, actionLabel: 'Find another stay', actionUrl: data.searchUrl }),
  bookingCancelled: (data) => shell({ heading: 'Booking cancelled', intro: `Booking ${data.bookingNumber} has been cancelled.`, body: '<p>Review the booking details in your account for the latest status.</p>', actionLabel: 'View booking', actionUrl: data.actionUrl }),
  bookingReminder: (data) => shell({ heading: 'Your Sohra stay is coming up', intro: `Check-in at ${data.propertyName} is on ${data.checkIn}.`, body: '<p>Keep your booking receipt and property contact details ready.</p>', actionLabel: 'View trip', actionUrl: data.actionUrl }),
  reviewRequest: (data) => shell({ heading: 'How was your stay?', intro: `Share your experience at ${data.propertyName}.`, body: '<p>Your review helps future guests and local hosts.</p>', actionLabel: 'Write a review', actionUrl: data.actionUrl }),
})
