import { useRef, useState } from 'react'
import { ImagePlus, LoaderCircle, Trash2 } from 'lucide-react'
import toast from 'react-hot-toast'
import { compressImage } from '../../utils/imageCompression'
export function ImageUploader({ label, multiple=false, imageUrl, onUpload, onDelete, maxImages=12 }) {
  const inputRef=useRef(null); const [busy,setBusy]=useState(false); const [previews,setPreviews]=useState([])
  const select=async(files)=>{const selected=Array.from(files).slice(0,maxImages);if(!selected.length)return;setPreviews(selected.map((f)=>URL.createObjectURL(f)));setBusy(true);try{for(const file of selected){await onUpload(await compressImage(file))}toast.success('Image uploaded.')}catch(e){toast.error(e.message)}finally{setBusy(false);setPreviews([]);if(inputRef.current)inputRef.current.value=''}}
  return <div><div className="mb-2 flex items-center justify-between"><label className="text-sm font-bold">{label}</label>{imageUrl&&onDelete&&<button type="button" onClick={onDelete} className="inline-flex items-center gap-1 text-xs font-bold text-red-600"><Trash2 size={14}/>Delete</button>}</div><button type="button" onClick={()=>inputRef.current?.click()} onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>{e.preventDefault();select(e.dataTransfer.files)}} className="flex min-h-36 w-full items-center justify-center overflow-hidden rounded-3xl border-2 border-dashed border-black/15 bg-white text-center focus-visible:outline-2 focus-visible:outline-[#3F7D58]">{imageUrl?<img src={imageUrl} alt={`${label} preview`} className="h-48 w-full object-cover"/>:<span className="p-6 text-sm text-muted">{busy?<LoaderCircle className="mx-auto mb-2 animate-spin"/>:<ImagePlus className="mx-auto mb-2"/>}Drag and drop or choose {multiple?'images':'an image'}</span>}</button>{previews.length>0&&<div className="mt-3 grid grid-cols-4 gap-2">{previews.map((url)=><img key={url} src={url} alt="Selected preview" className="h-20 w-full rounded-xl object-cover"/>)}</div>}<input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" multiple={multiple} className="sr-only" onChange={(e)=>select(e.target.files)} aria-label={`Upload ${label}`}/></div>
}
