import { useEffect, useState } from 'react'
import { Activity, Cloud, Database, HardDrive, RefreshCw, Users } from 'lucide-react'
import { AdminPageHeader } from '../../components/admin/AdminPageHeader'
import { runHealthCheck, getMonitoringMetrics } from '../../services/operationsService'

const statusClass = (status) => status === 'operational' ? 'bg-green-100 text-green-700' : status === 'secured' ? 'bg-blue-100 text-blue-700' : 'bg-red-100 text-red-700'
export default function AdminMonitoringPage(){
  const [health,setHealth]=useState(null);const[metrics,setMetrics]=useState(null);const[loading,setLoading]=useState(true)
  const load=async()=>{setLoading(true);const[h,m]=await Promise.all([runHealthCheck(),getMonitoringMetrics()]);setHealth(h);setMetrics(m);setLoading(false)}
  useEffect(()=>{load()},[])
  const cards=[['Users',metrics?.users||0,Users],['Bookings',metrics?.bookings||0,Activity],['Properties',metrics?.properties||0,Cloud],['Reviews',metrics?.reviews||0,Database]]
  return <div className="space-y-6"><AdminPageHeader title="System Monitoring" description="Live operational health and platform metrics." actions={<button onClick={load} className="inline-flex items-center gap-2 rounded-xl bg-black px-4 py-2 text-sm font-bold text-white"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon])=><article key={label} className="rounded-2xl bg-white p-5 shadow-sm"><Icon className="h-5 w-5 text-donroom-success"/><p className="mt-4 text-3xl font-black">{value}</p><p className="text-sm text-muted">{label}</p></article>)}</div><section className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Service health</h2><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusClass(health?.overall)}`}>{health?.overall||'checking'}</span></div><div className="mt-4 grid gap-3 md:grid-cols-2">{health?.checks?.map(item=><div key={item.name} className="rounded-xl border border-default p-4"><div className="flex items-center justify-between"><p className="font-bold">{item.name}</p><span className={`rounded-full px-2 py-1 text-xs font-bold ${statusClass(item.status)}`}>{item.status}</span></div><p className="mt-2 text-xs text-muted">Latency: {item.latencyMs} ms{item.error?` · ${item.error}`:''}</p></div>)}</div></section><section className="grid gap-4 lg:grid-cols-2"><article className="rounded-2xl bg-white p-5 shadow-sm"><HardDrive className="h-5 w-5 text-donroom-success"/><h2 className="mt-3 text-xl font-black">Runtime</h2><dl className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><dt>Version</dt><dd>{metrics?.version?.version}</dd></div><div className="flex justify-between"><dt>Build</dt><dd>{metrics?.version?.buildNumber}</dd></div><div className="flex justify-between"><dt>Release</dt><dd>{metrics?.version?.releaseDate}</dd></div><div className="flex justify-between"><dt>Server time</dt><dd>{metrics?.serverTime?new Date(metrics.serverTime).toLocaleString():'—'}</dd></div></dl></article><article className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Recent system events</h2><div className="mt-4 space-y-3">{metrics?.recentLogs?.length?metrics.recentLogs.slice(0,6).map(log=><div key={log.id} className="rounded-xl bg-black/[.03] p-3 text-sm"><p className="font-bold">{log.event}</p><p className="text-muted">{log.userId||'system'}</p></div>):<p className="text-sm text-muted">No system events recorded yet.</p>}</div></article></section></div>
}
