import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { AdminPageHeader } from '../../components/admin/AdminPageHeader'
import { DEFAULT_APP_SETTINGS, DEFAULT_FEATURE_FLAGS } from '../../constants/operations'
import { useAuth } from '../../hooks/useAuth'
import { useOperations } from '../../hooks/useOperations'
import { saveOperationalSettings } from '../../services/operationsService'

export default function AdminOperationsSettingsPage(){const{settings,flags,refresh}=useOperations();const{user}=useAuth();const[form,setForm]=useState(DEFAULT_APP_SETTINGS);const[featureFlags,setFeatureFlags]=useState(DEFAULT_FEATURE_FLAGS);const[saving,setSaving]=useState(false);useEffect(()=>{setForm(settings);setFeatureFlags(flags)},[settings,flags]);const save=async(e)=>{e.preventDefault();setSaving(true);try{await saveOperationalSettings({settings:form,flags:featureFlags,adminId:user.uid});await refresh();toast.success('Operational settings updated.')}catch(error){toast.error(error.message)}finally{setSaving(false)}};return <form onSubmit={save} className="space-y-6"><AdminPageHeader title="Operations Settings" description="Maintenance controls, global settings and feature flags."/><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Application settings</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{[['applicationName','Application name'],['supportEmail','Support email'],['supportPhone','Support phone'],['timezone','Timezone'],['currency','Currency'],['language','Default language'],['maxUploadSizeMb','Maximum upload size (MB)'],['maxBookingNights','Maximum booking nights']].map(([key,label])=><label key={key} className="text-sm font-bold">{label}<input value={form[key]} type={typeof form[key]==='number'?'number':'text'} onChange={e=>setForm({...form,[key]:typeof form[key]==='number'?Number(e.target.value):e.target.value})} className="mt-2 w-full rounded-xl border border-default px-3 py-2 font-normal"/></label>)}</div></section><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Maintenance mode</h2><label className="mt-4 flex items-center gap-3"><input type="checkbox" checked={form.maintenanceMode} onChange={e=>setForm({...form,maintenanceMode:e.target.checked})}/><span className="font-bold">Enable maintenance mode</span></label><label className="mt-4 block text-sm font-bold">Maintenance message<textarea value={form.maintenanceMessage} onChange={e=>setForm({...form,maintenanceMessage:e.target.value})} rows="3" className="mt-2 w-full rounded-xl border border-default p-3 font-normal"/></label></section><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Feature flags</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(featureFlags).map(([key,value])=><label key={key} className="flex items-center justify-between rounded-xl border border-default p-3"><span className="font-bold capitalize">{key.replace(/([A-Z])/g,' $1')}</span><input type="checkbox" checked={value} onChange={e=>setFeatureFlags({...featureFlags,[key]:e.target.checked})}/></label>)}</div></section><button disabled={saving} className="rounded-xl bg-black px-5 py-3 font-bold text-white disabled:opacity-50">{saving?'Saving…':'Save operations settings'}</button></form>}
